name: build-docs

on:
    push:
        branches:
          - "master"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup Python3
            uses: actions/setup-python@v5
            with:
                python-version: '3.12.3'

          - name: Install poetry
            run: python3 -m pip install poetry

          - name: Install dependencies
            run: python3 -m poetry install

          - name: Run sphinx
            run: |
                ./build-doc.sh
                tmpfile = $(mktemp)
                tail -n +5 docs_build/output/index.md > $tmpfile
                cat $tmpfile > docs_build/output/index.md

          - name: Move docs
            run: |
                rm -r docs || true
                mv docs_build/output docs
                rm -r docs_build

          - name: Check for docs changes
            id: docs_changes
            run: |
                git add -N docs
                git diff --exit-code
            continue-on-error: true

          - name: Commit & push
            run: |
                if ! git diff --exit-code --quiet; then
                    git config --local user.email "action@github.com"
                    git config --local user.name "actions-user"
                    git add docs
                    git commit -m "Generate docs"
                    git push origin master
                fi
            if: steps.docs_changes.outcome == 'failure'
